### ISSUE TITLE
1.19 release checklist

### ISSUE THREAD

**Issue by williewillus** [Vazkii/Botania#4126]
### Mod Loader

Both Fabric and Forge (I confirm that I have tested both loaders and will specify both loader versions below)

### Minecraft Version

1.19.2

### Botania version

next

### Modloader version

any

### The latest.log file

none

### Issue description

Just publishing this list so that anyone can help pitch in

- [x] fix floating flower item models on Forge
- [x] datagenerate the marimorphosis biome tags that still haven't been generated
- [x] clean sketchy TODOs in JEI integration
- [ ] new features
- [x] fix corporea interceptors/retainers being completely broken

**Comment by artemisSystem** [comment]
note that we have the docs/1.19-notes.org file, which notes some breaking changes that are nice to get done before initial release

**Comment by williewillus** [comment]
closing since all the major points were covered (new features separately)
